### ISSUE TITLE
error Paginate: 'pager size' must be a positive integer

### ISSUE THREAD

**Issue by xilu0** [opera7133/Blonde#118]
i have a problem:
`[watch:*hugo] Error: Error building site: failed to render pages: render of "home" failed: "/home/azureuser/baida/themes/Blonde/layouts/_default/list.html:12:32": execute of template failed: template: _default/list.html:12:32: executing "main" at <.Paginate>: error calling Paginate: 'pager size' must be a positive integer`
help me, please!

**Comment by xilu0** [comment]
my host:
```
[root@test baida]# hugo version
hugo v0.94.2-48FB9E4D linux/amd64 BuildDate=2022-03-12T10:28:42Z VendorInfo=gohugoio
```

**Comment by opera7133** [comment]
Is `paginator_pages` set correctly in `params` in `config.toml`?
I don't think it is a code issue, as I have had similar Issue before.

**Comment by xilu0** [comment]
i set follows params, but the error is not gone.
```
baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'blonde'


[params]
paginate = 10
RegularPages = 5
```

**Comment by xilu0** [comment]
can you give a example or default params?

**Comment by opera7133** [comment]
As mentioned in the README, please refer to `exampleSite/config.toml`.
