### ISSUE TITLE
Add a random / popular posts widget to the sidebar

### ISSUE THREAD

**Issue by SamHamou** [opera7133/Blonde#12]
Hey can you add a random / popular posts widget to this theme, i tried to add it myself but im still new to tailwind css in one of my websites i use this code to show random posts [link to the code](https://github.com/SamHamou/Tahmil/blob/master/themes/Tahmil/layouts/partials/widgets/recent.html)

**Comment by opera7133** [comment]
Added a widget for random posts.
If you don't like the style, you can adjust it yourself :)

**Comment by SamHamou** [comment]
thank you :) i loved it
