### ISSUE TITLE
Widgets display out of order on post pages

### ISSUE THREAD

**Issue by Gunther0042** [opera7133/Blonde#121]
Reordering the widgets using the params.widgets.widgets parameter in the config.toml file yields the correct ordering of widgets on the home (list?) page, but not on the post pages.

My hunch is that it has to do with the code in layouts/_default/list.html having the following:
```
  {{ if .Site.Params.widgets.display }}
    {{ partial "widgets.html" . }}
  {{ end }}
```
While layouts/_default/single.html has:
```
        {{ if .Site.Params.widgets.display }}
        <div class="hidden lg:block lg:col-span-1">
            {{ partial "widgets/search.html" . }}
            {{ partial "widgets/archive.html" . }}
            {{ partial "widgets/category.html" . }}
            {{ partial "widgets/tags.html" . }}
            {{ partial "widgets/recent.html" . }}
        </div>
        {{ end }}
```
But I am not familiar enough with the code to be sure. If I am correct though, I imagine it is a simple fix.

**Comment by opera7133** [comment]
I'll fix it as soon as I can.

**Comment by Gunther0042** [comment]
Thank you for the quick response. I appreciate your hard work on the theme!

**Comment by opera7133** [comment]
I just replaced the code, but I think I fixed it.
