### ISSUE TITLE
Add a search bar to the theme

### ISSUE THREAD

**Issue by SamHamou** [opera7133/Blonde#14]
Hell. can you add a search bar feature to the widgets in this theme it doesn't have to be an internal search engine just a #search bar that take you to google something like this one in this theme [Mainroad theme](https://github.com/Vimux/Mainroad/blob/master/layouts/partials/widgets/search.html)  
 demo site to check it : https://mainroad-demo.netlify.app/

**Comment by opera7133** [comment]
The search bar was created using Google search with reference to the Mainroad theme.
If you want to implement a full-text search with high functionality, you can use [Lunr.js](https://github.com/olivernn/lunr.js/) and [lunr-languages](https://github.com/MihaiValentin/lunr-languages) to create it. (It's a bit cumbersome, though.)

**Comment by SamHamou** [comment]
thank you very much 👍  google search is enough for me  :)
