### ISSUE TITLE
The second title(?) of the blog seems to be forcibly lowercased

### ISSUE THREAD

**Issue by mhatta** [opera7133/Blonde#16]
![image](https://user-images.githubusercontent.com/44892/111261650-21653880-8666-11eb-9036-4fb2fe905719.png)

Note "H"atta and "h"atta in the pic.   I guess it's Tailwind CSS's handling, but not sure.

**Comment by opera7133** [comment]
Probably it's because of Hugo's Humanize process.
In this process, the first letter of the argument is capitalized, and the other letters are lowercased.
https://gohugo.io/functions/humanize/
