### ISSUE TITLE
Viewport tag

### ISSUE THREAD

**Issue by phaitonican** [opera7133/Blonde#43]
It says in Google Chrome the viewport tag is missing but I actually find it in head.html. Howcome it only scores 70 on SEO i wanted to change it but i couldnt.
![Bildschirmfoto vom 2021-06-13 23-34-31](https://user-images.githubusercontent.com/25594670/121822536-ddeb8c00-cc9f-11eb-983d-7abf6fa0b74a.png)

**Comment by phaitonican** [comment]
![Bildschirmfoto vom 2021-06-13 23-34-31](https://user-images.githubusercontent.com/25594670/121822536-ddeb8c00-cc9f-11eb-983d-7abf6fa0b74a.png)

**Comment by opera7133** [comment]
I don't know why, but I modified some of the code to try it out and was able to get 100 scores for SEO.
Perhaps this commit has something to do with it : 431cc90

![image](https://user-images.githubusercontent.com/39876629/121852542-9a8a2f80-cd2a-11eb-80f8-60f00b90f9d2.png)

**Comment by phaitonican** [comment]
Thanks a lot! Yea it works thanks! I'll let this open until merged then :)

**Comment by opera7133** [comment]
Um, that's a commit on the master branch, so I don't think I need to merge it...

**Comment by phaitonican** [comment]
Omg sorry, I'm little new my bad.
