### ISSUE TITLE
Toggle DarkMode on Live

### ISSUE THREAD

**Issue by juliangeissler** [opera7133/Blonde#51]
Hey,
first up, thank you for the theme.

I got the following issue that the theme toggle on my live site doesnt respond. In the Local Storage the Value of the KeyPair gets toggled, but the display doesnt change. On my local setup it works.
What could I miss on my live setup? 
The console doesnt output anything, maybe you have an idea

I saw in the code that basically the icons get removed and added and the value of 'theme' gets set.

Other things:
- I also set the variable 'darkmode' to 'light' in my config.toml
- Disabled adblock
- disabled Dark Reader
- tried Chrome and Firefox

Thanks

**Comment by opera7133** [comment]
Try opening the Developer Tools in your browser first. (Not local)
If the icon does not switch when you press the button, or if ```class="dark"``` is not added to the ```<html>```, then there is a problem with the JavaScript loading.
If the dark class is given correctly, it is a CSS problem. (I don't expect that problem to occur.)

**Comment by juliangeissler** [comment]
On live when I press the button the icon switches and the `class="dark` is added to the html tag. For example the css rules for the first div with classes `min-h-screen flex flex-col bg-gray-100 dark:bg-warmgray-800` dont switch

**Comment by juliangeissler** [comment]
I found it :)
It was an issue with old resource css files
Again, Should they be in the repository? Or should hugo generate them on deployment?

Thanks for the quick help

**Comment by opera7133** [comment]
I don't think it's necessary to have a resources folder in the repository, because Hugo will generate one every time it builds.

**Comment by juliangeissler** [comment]
Ok, I will add the folder to my .gitignore. Thanks again!
