### ISSUE TITLE
thumbnail's width and height problem

### ISSUE THREAD

**Issue by SamHamou** [opera7133/Blonde#9]
Hello how i can change the width and height of the thumbnails in the home page  i tried to modify the summary.html file but it didn't work

**Comment by opera7133** [comment]
OK, for the moment, I have added a parameter to config.toml to adjust the height of the image. 
If you want to make the height smaller than h-32, you need to remove some Padding in summary.html.

**Comment by SamHamou** [comment]
thank you, and what about the width of the thumbnails' i want to make it 200px

**Comment by opera7133** [comment]
Added a parameter to set the width of the image.
If you want to set the width to 200px, set ```thumbnail_height``` to ```h-auto``` and ```thumbnail_width``` to ```w-56``` or ```w-64```.

**Comment by SamHamou** [comment]
i have updated the theme with the changes you have made but somehow it's not working this is my test website : https://kalima.netlify.app/

**Comment by opera7133** [comment]
Temporarily added w-56 and lg:h-auto to CSS. 
Perhaps this is because either hugo_stats.json has not been updated properly or resources has not been updated.

**Comment by SamHamou** [comment]
thank you it's working now
