### ISSUE TITLE
Error: Error building site: POSTCSS: failed to transform "css/styles.css" (text/css): warn - As of Tailwind CSS v3.0, `coolGray` has been renamed to `gray`.

### ISSUE THREAD

**Issue by Gys** [opera7133/Blonde#97]
Hi!

First time user of Hugo. On my first install I ran into this error. I do not know much about node and Tailwind unfortunately. 

From https://gohugo.io/getting-started/quick-start/:
- followed step 1
- followed step 2

From https://themes.gohugo.io/themes/blonde/:
- followed Prerequisites
- followed installation method 1
- did npm install
- copied themes/Blonde/exampleSite/config.toml to overwrite root config.toml (to be identical, no changes)

Running `hugo server` results in:

````
hugo v0.90.1+extended darwin/amd64 BuildDate=unknown
Error: Error building site: POSTCSS: failed to transform "css/styles.css" (text/css): warn - As of Tailwind CSS v3.0, `coolGray` has been renamed to `gray`.
warn - Update your configuration file to silence this warning.
Error: ENOENT: no such file or directory, stat '/Users/XXXX/golang/src/bitbucket.org/XXXX/YYYY/hugo-website/stdin'
````

MacOS 12.0.1
npm 16.5.0

**Comment by opera7133** [comment]
I forgot that there was a change in Tailwind CSS v3.
I'll fix it soon.

**Comment by opera7133** [comment]
Fixed it.
I made some changes to README.md, so please check it carefully.
